name: the_one_sdk
description: A plugin for integrating with The One API https://the-one-api.dev/.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  http: 0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
